# site settings
title: Kristina Horn
subtitle: Programming, Design & more
email: kristina-horn@gmx.ch
description: I'm a computional-linguistics student at UZH try. This site is a small collection of different projects from my studies.
baseurl: 
url: # the base hostname & protocol for your site
author: Kristina
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/k-horn
  GitLab: https://gitl
  LinkedIn: https://www.linkedin.com/in/kristina-horn-10729b1b1/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
